name: CribbageApp
options:
  bundleIdPrefix: com.cribbage
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  CribbageApp:
    type: application
    platform: iOS
    sources:
      - CribbageApp
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.cribbage.CribbageApp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        SWIFT_STRICT_CONCURRENCY: minimal

  CribbageAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CribbageAppTests
    dependencies:
      - target: CribbageApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/CribbageApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/CribbageApp"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  CribbageApp:
    build:
      targets:
        CribbageApp: all
        CribbageAppTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CribbageAppTests
